# fly.toml app configuration file generated for booster2024 on 2024-03-09T19:12:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'booster2024'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8043
  processes = ['app']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
